/**
 * @author Bodhana S.
 * @date June 8, 2022 
 * Rules window of game, which include a RETURN button to navigate back to the main menu
 */
package sivagurunathanbattleship;

public class Rules extends javax.swing.JFrame {

    private WelcomePage welcome; //Initializes instance of main menu window

    public Rules(WelcomePage m) {
        initComponents();
        welcome = m;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeMessage = new javax.swing.JPanel();
        instructionsText2 = new javax.swing.JLabel();
        instructionsText1 = new javax.swing.JLabel();
        instructionsText3 = new javax.swing.JLabel();
        instructionsText4 = new javax.swing.JLabel();
        instructionsText5 = new javax.swing.JLabel();
        instructionsText6 = new javax.swing.JLabel();
        instructionsText7 = new javax.swing.JLabel();
        rulesLbl = new javax.swing.JLabel();
        instructionsText8 = new javax.swing.JLabel();
        returnBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeMessage.setBackground(new java.awt.Color(255, 255, 255));
        welcomeMessage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        instructionsText2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        instructionsText2.setText("same ship must be adjacent to one another. Click on the square");

        instructionsText1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        instructionsText1.setText("2. Click on a square where you think an opponent ship is. If ");
        instructionsText1.setToolTipText("");

        instructionsText3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        instructionsText3.setText("1. Select squares to represent your 5 ships. Squares of the");
        instructionsText3.setToolTipText("");

        instructionsText4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        instructionsText4.setText("you selected right, then you attack again. Otherwise, it is ");
        instructionsText4.setToolTipText("");

        instructionsText5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        instructionsText5.setText("your opponent’s turn. Players should not look at their ");
        instructionsText5.setToolTipText("");

        instructionsText6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        instructionsText6.setText("opponent’s board, so turn around when it is not your turn. ");
        instructionsText6.setToolTipText("");

        instructionsText7.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        instructionsText7.setText("3. First person to “hit” all 5 ships is the winner!");
        instructionsText7.setToolTipText("");

        rulesLbl.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        rulesLbl.setForeground(new java.awt.Color(255, 153, 0));
        rulesLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rulesLbl.setText("Rules");

        instructionsText8.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        instructionsText8.setText("again to remove the \"ship\" and select another square.");

        javax.swing.GroupLayout welcomeMessageLayout = new javax.swing.GroupLayout(welcomeMessage);
        welcomeMessage.setLayout(welcomeMessageLayout);
        welcomeMessageLayout.setHorizontalGroup(
            welcomeMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomeMessageLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(welcomeMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(instructionsText7, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instructionsText6, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instructionsText5, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instructionsText4, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instructionsText1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instructionsText8)
                    .addComponent(instructionsText3)
                    .addComponent(rulesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instructionsText2))
                .addGap(0, 16, Short.MAX_VALUE))
        );
        welcomeMessageLayout.setVerticalGroup(
            welcomeMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomeMessageLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(rulesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(instructionsText3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instructionsText2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instructionsText8)
                .addGap(18, 18, 18)
                .addComponent(instructionsText1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instructionsText4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instructionsText5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instructionsText6)
                .addGap(18, 18, 18)
                .addComponent(instructionsText7)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        returnBtn.setBackground(new java.awt.Color(255, 255, 255));
        returnBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        returnBtn.setForeground(new java.awt.Color(0, 153, 0));
        returnBtn.setText("Return");
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(welcomeMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(returnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(welcomeMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(returnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Navigates back to the main menu when button is clicked
     */
    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        welcome.setVisible(true); //Displays main menu
        this.setVisible(false);//Closes rule page
    }//GEN-LAST:event_returnBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rules(welcome).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel instructionsText1;
    private javax.swing.JLabel instructionsText2;
    private javax.swing.JLabel instructionsText3;
    private javax.swing.JLabel instructionsText4;
    private javax.swing.JLabel instructionsText5;
    private javax.swing.JLabel instructionsText6;
    private javax.swing.JLabel instructionsText7;
    private javax.swing.JLabel instructionsText8;
    private javax.swing.JButton returnBtn;
    private javax.swing.JLabel rulesLbl;
    private javax.swing.JPanel welcomeMessage;
    // End of variables declaration//GEN-END:variables
}
