/**
 * @author Bodhana S.
 * @date June 8, 2022 Main menu window of game with buttons to play, refresh on
 * rules, and quit
 */
package sivagurunathanbattleship;

import javax.swing.JOptionPane;

public class WelcomePage extends javax.swing.JFrame {

    public WelcomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeMessage = new javax.swing.JPanel();
        welcomeText = new javax.swing.JLabel();
        goodLuck = new javax.swing.JLabel();
        playBtn = new javax.swing.JButton();
        rulesBtn = new javax.swing.JButton();
        quitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeMessage.setBackground(new java.awt.Color(255, 255, 255));
        welcomeMessage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        welcomeText.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        welcomeText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeText.setText("Welcome to BATTLESHIP!");

        goodLuck.setFont(new java.awt.Font("Microsoft YaHei UI", 2, 14)); // NOI18N
        goodLuck.setText("May the ships ever be in your favour...");

        javax.swing.GroupLayout welcomeMessageLayout = new javax.swing.GroupLayout(welcomeMessage);
        welcomeMessage.setLayout(welcomeMessageLayout);
        welcomeMessageLayout.setHorizontalGroup(
            welcomeMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomeMessageLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(welcomeMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomeMessageLayout.createSequentialGroup()
                        .addComponent(welcomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomeMessageLayout.createSequentialGroup()
                        .addComponent(goodLuck, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
        );
        welcomeMessageLayout.setVerticalGroup(
            welcomeMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomeMessageLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(welcomeText)
                .addGap(18, 18, 18)
                .addComponent(goodLuck)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        playBtn.setBackground(new java.awt.Color(255, 255, 255));
        playBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        playBtn.setForeground(new java.awt.Color(0, 153, 0));
        playBtn.setText("Play");
        playBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playBtnActionPerformed(evt);
            }
        });

        rulesBtn.setBackground(new java.awt.Color(255, 255, 255));
        rulesBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        rulesBtn.setForeground(new java.awt.Color(255, 153, 0));
        rulesBtn.setText("Rules");
        rulesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rulesBtnActionPerformed(evt);
            }
        });

        quitBtn.setBackground(new java.awt.Color(255, 255, 255));
        quitBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        quitBtn.setForeground(new java.awt.Color(255, 0, 0));
        quitBtn.setText("Quit");
        quitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(playBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(rulesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(quitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(welcomeMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(welcomeMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rulesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Rules rules; //Declare instance of Rules window

    /**
     * Displays Player 1's Fleet Grid to choose location of their ships when PLAY button is clicked
     */
    private void playBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playBtnActionPerformed
        //Reminder to Player 2 to turn around while Player 1 selects their ship locations
        JOptionPane.showMessageDialog(null, "REMINDER: Player 2, please turn around, so Player 1 can set their board.");
        //Creates instance if Player 1's Fleet Grid does not exist yet
        if (PlayerReferences.player1inst == null) {
            PlayerReferences.player1inst = new Player1FleetLocationGrid();
        }
        PlayerReferences.player1inst.setVisible(true); //Otherwise, sets the window visible to user
        this.setVisible(false); //Closes main menu
    }//GEN-LAST:event_playBtnActionPerformed
    /**
     * Displays rules page when RULES button is clicked
     */
    private void rulesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rulesBtnActionPerformed
        //Refer WelcomePage.playBtnActionPerformed comments
        if (rules == null) {
            rules = new Rules(this);
        }
        rules.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_rulesBtnActionPerformed
    /**
     * Terminates program when QUIT button is clicked
     */
    private void quitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel goodLuck;
    private javax.swing.JButton playBtn;
    private javax.swing.JButton quitBtn;
    private javax.swing.JButton rulesBtn;
    private javax.swing.JPanel welcomeMessage;
    private javax.swing.JLabel welcomeText;
    // End of variables declaration//GEN-END:variables
}
